server:
  port: 8080 # 后端访问端口
  servlet:
    context-path: /aoi/ # 对外接口前缀

logging:
  config: classpath:log4j2.xml # log4j2配置文件

mybatis-plus:
  configuration:
    cache-enabled: false # 关闭二级缓存
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开始sql打印

spring:
  profiles:
    active: dev
  messages:
    basename: i18n/error/description,i18n/error/solution
